[2024-06-28T17:48:38.668+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T17:48:38.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:48:27.704418+00:00 [queued]>
[2024-06-28T17:48:38.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:48:27.704418+00:00 [queued]>
[2024-06-28T17:48:38.696+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T17:48:38.707+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 17:48:27.704418+00:00
[2024-06-28T17:48:38.713+0000] {standard_task_runner.py:63} INFO - Started process 149 to run task
[2024-06-28T17:48:38.716+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T17:48:27.704418+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmppl43g7jj']
[2024-06-28T17:48:38.719+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask data_delivery
[2024-06-28T17:48:38.762+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:48:27.704418+00:00 [running]> on host 79a59ce16f65
[2024-06-28T17:48:39.001+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T17:48:27.704418+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T17:48:27.704418+00:00'
[2024-06-28T17:48:39.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T17:48:39.011+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T17:48:39.011+0000] {Load_Data.py:73} INFO - Loading location Dimension ...
[2024-06-28T17:48:39.011+0000] {Load_Data.py:147} INFO - Error loading location dimension: local variable 'DimLocation_df' referenced before assignment
[2024-06-28T17:48:39.011+0000] {Load_Data.py:151} INFO - loading DimRate Dimension ...
[2024-06-28T17:48:39.014+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T17:48:39.018+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:48:39.024+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T17:48:39.024+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:48:39.025+0000] {Load_Data.py:154} INFO - DimRate_df dimension loaded successfully
[2024-06-28T17:48:39.025+0000] {Load_Data.py:169} INFO - loading payment dimension....
[2024-06-28T17:48:39.026+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T17:48:39.029+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:48:39.035+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T17:48:39.035+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:48:39.035+0000] {Load_Data.py:172} INFO - payment_df dimension loaded successfully
[2024-06-28T17:48:39.036+0000] {Load_Data.py:11} INFO - Loading vendor Dimension ...
[2024-06-28T17:48:39.040+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:48:39.045+0000] {Load_Data.py:69} INFO - Error loading vendor dimension: 'vendor_name'
[2024-06-28T17:48:39.045+0000] {Load_Data.py:160} INFO - loading trip_type dimension....
[2024-06-28T17:48:39.047+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T17:48:39.051+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:48:39.055+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T17:48:39.056+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:48:39.056+0000] {Load_Data.py:163} INFO - trip_df dimension loaded successfully
[2024-06-28T17:48:39.056+0000] {Load_Data.py:178} INFO - loading fact table ....
[2024-06-28T17:48:42.393+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T17:48:42.396+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:50:09.515+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T17:50:09.516+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T17:50:09.517+0000] {process_utils.py:132} INFO - Sending 15 to group 149. PIDs of all processes in the group: [149]
[2024-06-28T17:50:09.518+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 149
[2024-06-28T17:50:09.518+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T17:50:09.521+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T17:50:09.730+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=149, status='terminated', exitcode=0, started='17:48:38') (149) terminated with exit code 0
