[2024-06-28T22:53:29.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T22:53:29.674+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T22:53:25.596845+00:00 [queued]>
[2024-06-28T22:53:29.682+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T22:53:25.596845+00:00 [queued]>
[2024-06-28T22:53:29.683+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T22:53:29.694+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 22:53:25.596845+00:00
[2024-06-28T22:53:29.701+0000] {standard_task_runner.py:63} INFO - Started process 484 to run task
[2024-06-28T22:53:29.704+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T22:53:25.596845+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpuznnpc8c']
[2024-06-28T22:53:29.707+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask data_delivery
[2024-06-28T22:53:29.745+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T22:53:25.596845+00:00 [running]> on host 79a59ce16f65
[2024-06-28T22:53:29.985+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T22:53:25.596845+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T22:53:25.596845+00:00'
[2024-06-28T22:53:29.987+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T22:53:29.997+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T22:53:29.998+0000] {Load_Data.py:20} INFO - Loading location Dimension ...
[2024-06-28T22:53:30.006+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:53:30.011+0000] {Load_Data.py:36} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T22:53:30.013+0000] {Load_Data.py:94} INFO - Error loading location dimension: syntax error at end of input
LINE 5:                             
                                    ^

[2024-06-28T22:53:30.013+0000] {Load_Data.py:99} INFO - loading DimRate Dimension ...
[2024-06-28T22:53:30.015+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T22:53:30.019+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:53:30.025+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T22:53:30.026+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:53:30.026+0000] {Load_Data.py:102} INFO - DimRate_df dimension loaded successfully
[2024-06-28T22:53:30.026+0000] {Load_Data.py:117} INFO - loading payment dimension....
[2024-06-28T22:53:30.028+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T22:53:30.031+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:53:30.038+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T22:53:30.039+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:53:30.039+0000] {Load_Data.py:120} INFO - payment_df dimension loaded successfully
[2024-06-28T22:53:30.039+0000] {Load_Data.py:11} INFO - loading Dimvendor Dimension ...
[2024-06-28T22:53:30.041+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-28T22:53:30.044+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:53:30.049+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-28T22:53:30.049+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:53:30.049+0000] {Load_Data.py:14} INFO - Dimvedor_df dimension loaded successfully
[2024-06-28T22:53:30.050+0000] {Load_Data.py:108} INFO - loading trip_type dimension....
[2024-06-28T22:53:30.052+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T22:53:30.056+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:53:30.061+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T22:53:30.061+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:53:30.061+0000] {Load_Data.py:111} INFO - trip_df dimension loaded successfully
[2024-06-28T22:53:30.062+0000] {Load_Data.py:126} INFO - loading fact table ....
[2024-06-28T22:53:33.683+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T22:53:33.686+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:56:16.309+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T22:56:16.311+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T22:56:16.313+0000] {process_utils.py:132} INFO - Sending 15 to group 484. PIDs of all processes in the group: [484]
[2024-06-28T22:56:16.313+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 484
[2024-06-28T22:56:16.313+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T22:56:16.318+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T22:56:16.526+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=484, status='terminated', exitcode=0, started='22:53:29') (484) terminated with exit code 0
