[2024-06-28T21:58:11.558+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T21:58:11.583+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:58:08.311888+00:00 [queued]>
[2024-06-28T21:58:11.592+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:58:08.311888+00:00 [queued]>
[2024-06-28T21:58:11.592+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T21:58:11.605+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 21:58:08.311888+00:00
[2024-06-28T21:58:11.612+0000] {standard_task_runner.py:63} INFO - Started process 385 to run task
[2024-06-28T21:58:11.615+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T21:58:08.311888+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp9xqqf4x3']
[2024-06-28T21:58:11.618+0000] {standard_task_runner.py:91} INFO - Job 137: Subtask data_delivery
[2024-06-28T21:58:11.663+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:58:08.311888+00:00 [running]> on host 79a59ce16f65
[2024-06-28T21:58:11.914+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T21:58:08.311888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T21:58:08.311888+00:00'
[2024-06-28T21:58:11.915+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T21:58:11.925+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T21:58:11.925+0000] {Load_Data.py:20} INFO - Loading location Dimension ...
[2024-06-28T21:58:11.932+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:58:50.087+0000] {Load_Data.py:36} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T21:58:50.231+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:58:50.233+0000] {Table_creation.py:30} INFO - Loading data into table DimLocation...
[2024-06-28T21:58:50.236+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:58:50.247+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimLocation With 3 Row
[2024-06-28T21:58:50.248+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:58:50.248+0000] {Load_Data.py:90} INFO - DimLocation dimension loaded successfully
[2024-06-28T21:58:50.248+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:58:50.249+0000] {Load_Data.py:98} INFO - loading DimRate Dimension ...
[2024-06-28T21:58:50.251+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T21:58:50.254+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:58:50.263+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T21:58:50.264+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:58:50.264+0000] {Load_Data.py:101} INFO - DimRate_df dimension loaded successfully
[2024-06-28T21:58:50.264+0000] {Load_Data.py:116} INFO - loading payment dimension....
[2024-06-28T21:58:50.267+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T21:58:50.269+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:58:50.276+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T21:58:50.276+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:58:50.276+0000] {Load_Data.py:119} INFO - payment_df dimension loaded successfully
[2024-06-28T21:58:50.276+0000] {Load_Data.py:11} INFO - loading Dimvendor Dimension ...
[2024-06-28T21:58:50.278+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-28T21:58:50.282+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:58:50.287+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-28T21:58:50.287+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:58:50.288+0000] {Load_Data.py:14} INFO - Dimvedor_df dimension loaded successfully
[2024-06-28T21:58:50.288+0000] {Load_Data.py:107} INFO - loading trip_type dimension....
[2024-06-28T21:58:50.289+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T21:58:50.293+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:58:50.299+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T21:58:50.300+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:58:50.300+0000] {Load_Data.py:110} INFO - trip_df dimension loaded successfully
[2024-06-28T21:58:50.300+0000] {Load_Data.py:125} INFO - loading fact table ....
[2024-06-28T21:58:53.722+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T21:58:53.726+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:00:53.049+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T22:00:53.051+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T22:00:53.053+0000] {process_utils.py:132} INFO - Sending 15 to group 385. PIDs of all processes in the group: [385]
[2024-06-28T22:00:53.053+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 385
[2024-06-28T22:00:53.053+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T22:00:53.056+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T22:00:53.266+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=385, status='terminated', exitcode=0, started='21:58:11') (385) terminated with exit code 0
