[2024-06-28T21:36:14.640+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T21:36:14.660+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:36:10.512062+00:00 [queued]>
[2024-06-28T21:36:14.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:36:10.512062+00:00 [queued]>
[2024-06-28T21:36:14.670+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T21:36:14.682+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 21:36:10.512062+00:00
[2024-06-28T21:36:14.689+0000] {standard_task_runner.py:63} INFO - Started process 358 to run task
[2024-06-28T21:36:14.691+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T21:36:10.512062+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp4fdsr5mw']
[2024-06-28T21:36:14.694+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask data_delivery
[2024-06-28T21:36:14.734+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:36:10.512062+00:00 [running]> on host 79a59ce16f65
[2024-06-28T21:36:14.987+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T21:36:10.512062+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T21:36:10.512062+00:00'
[2024-06-28T21:36:14.988+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T21:36:14.998+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T21:36:14.998+0000] {Load_Data.py:21} INFO - Loading location Dimension ...
[2024-06-28T21:36:15.005+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:36:15.007+0000] {Load_Data.py:36} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T21:36:15.166+0000] {Table_creation.py:51} INFO - Loading data into table DimLocation...
[2024-06-28T21:36:15.169+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:36:15.170+0000] {Load_Data.py:91} INFO - Error loading location dimension: duplicate key value violates unique constraint "dimlocation_pkey"
DETAIL:  Key (locationid, version)=(1, 1) already exists.

[2024-06-28T21:36:15.171+0000] {Load_Data.py:96} INFO - loading DimRate Dimension ...
[2024-06-28T21:36:15.173+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T21:36:15.175+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:36:15.182+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T21:36:15.182+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:36:15.183+0000] {Load_Data.py:99} INFO - DimRate_df dimension loaded successfully
[2024-06-28T21:36:15.183+0000] {Load_Data.py:114} INFO - loading payment dimension....
[2024-06-28T21:36:15.184+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T21:36:15.187+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:36:15.193+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T21:36:15.193+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:36:15.193+0000] {Load_Data.py:117} INFO - payment_df dimension loaded successfully
[2024-06-28T21:36:15.193+0000] {Load_Data.py:11} INFO - loading Dimvendor Dimension ...
[2024-06-28T21:36:15.195+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-28T21:36:15.197+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:36:15.203+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-28T21:36:15.203+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:36:15.203+0000] {Load_Data.py:14} INFO - Dimvedor_df dimension loaded successfully
[2024-06-28T21:36:15.203+0000] {Load_Data.py:105} INFO - loading trip_type dimension....
[2024-06-28T21:36:15.205+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T21:36:15.208+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:36:15.213+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T21:36:15.213+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:36:15.214+0000] {Load_Data.py:108} INFO - trip_df dimension loaded successfully
[2024-06-28T21:36:15.214+0000] {Load_Data.py:123} INFO - loading fact table ....
[2024-06-28T21:36:19.105+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T21:36:19.108+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:37:10.220+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T21:37:10.226+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T21:37:10.228+0000] {process_utils.py:132} INFO - Sending 15 to group 358. PIDs of all processes in the group: [358]
[2024-06-28T21:37:10.228+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 358
[2024-06-28T21:37:10.229+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T21:37:10.234+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T21:37:10.482+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=358, status='terminated', exitcode=0, started='21:36:14') (358) terminated with exit code 0
