[2024-06-14T08:13:34.180+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T08:13:34.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.database_preparation scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T08:13:34.210+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.database_preparation scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T08:13:34.211+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T08:13:34.224+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): database_preparation> on 2024-06-13 00:00:00+00:00
[2024-06-14T08:13:34.231+0000] {standard_task_runner.py:63} INFO - Started process 51 to run task
[2024-06-14T08:13:34.234+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'database_preparation', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpguhlbq9a']
[2024-06-14T08:13:34.236+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask database_preparation
[2024-06-14T08:13:34.280+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.database_preparation scheduled__2024-06-13T00:00:00+00:00 [running]> on host 762c91fd0326
[2024-06-14T08:13:34.494+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='database_preparation' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T08:13:34.495+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T08:13:34.505+0000] {NYC_Taxi_pipeline.py:37} INFO - database_preparation started
[2024-06-14T08:13:34.505+0000] {Table_creation.py:8} INFO - Create tables ......
[2024-06-14T08:13:34.507+0000] {db_utils.py:24} ERROR - Error while connecting to PostgreSQL: connection to server at "172.20.0.3", port 5432 failed: FATAL:  database "NYC_Taxi" does not exist

[2024-06-14T08:13:34.508+0000] {Table_creation.py:26} INFO - Failed to establish a connection to the database
[2024-06-14T08:13:34.508+0000] {NYC_Taxi_pipeline.py:39} INFO - database_preparation done
[2024-06-14T08:13:34.508+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-14T08:13:34.508+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T08:13:34.516+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=database_preparation, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T081334, end_date=20240614T081334
[2024-06-14T08:13:34.567+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-14T08:13:34.602+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-14T08:13:34.603+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
