[2024-06-28T17:57:50.806+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T17:57:50.828+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:57:39.496888+00:00 [queued]>
[2024-06-28T17:57:50.836+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:57:39.496888+00:00 [queued]>
[2024-06-28T17:57:50.836+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T17:57:50.847+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 17:57:39.496888+00:00
[2024-06-28T17:57:50.855+0000] {standard_task_runner.py:63} INFO - Started process 176 to run task
[2024-06-28T17:57:50.858+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T17:57:39.496888+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpdlsvyb2_']
[2024-06-28T17:57:50.861+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask data_delivery
[2024-06-28T17:57:50.900+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:57:39.496888+00:00 [running]> on host 79a59ce16f65
[2024-06-28T17:57:51.140+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T17:57:39.496888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T17:57:39.496888+00:00'
[2024-06-28T17:57:51.141+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T17:57:51.150+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T17:57:51.151+0000] {Load_Data.py:73} INFO - Loading location Dimension ...
[2024-06-28T17:57:51.158+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:57:51.162+0000] {Load_Data.py:89} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T17:57:51.163+0000] {Load_Data.py:143} INFO - Error loading location dimension: 'LocationID'
[2024-06-28T17:57:51.163+0000] {Load_Data.py:147} INFO - loading DimRate Dimension ...
[2024-06-28T17:57:51.165+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T17:57:51.168+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:57:51.175+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T17:57:51.175+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:57:51.175+0000] {Load_Data.py:150} INFO - DimRate_df dimension loaded successfully
[2024-06-28T17:57:51.175+0000] {Load_Data.py:165} INFO - loading payment dimension....
[2024-06-28T17:57:51.177+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T17:57:51.180+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:57:51.185+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T17:57:51.186+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:57:51.186+0000] {Load_Data.py:168} INFO - payment_df dimension loaded successfully
[2024-06-28T17:57:51.186+0000] {Load_Data.py:11} INFO - Loading vendor Dimension ...
[2024-06-28T17:57:51.191+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:57:51.195+0000] {Load_Data.py:69} INFO - Error loading vendor dimension: 'vendor_name'
[2024-06-28T17:57:51.195+0000] {Load_Data.py:156} INFO - loading trip_type dimension....
[2024-06-28T17:57:51.198+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T17:57:51.201+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:57:51.205+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T17:57:51.205+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:57:51.206+0000] {Load_Data.py:159} INFO - trip_df dimension loaded successfully
[2024-06-28T17:57:51.206+0000] {Load_Data.py:174} INFO - loading fact table ....
[2024-06-28T17:57:54.713+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T17:57:54.716+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:58:16.093+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T17:58:16.094+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T17:58:16.096+0000] {process_utils.py:132} INFO - Sending 15 to group 176. PIDs of all processes in the group: [176]
[2024-06-28T17:58:16.096+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 176
[2024-06-28T17:58:16.096+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T17:58:16.102+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T17:58:16.269+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=176, status='terminated', exitcode=0, started='17:57:50') (176) terminated with exit code 0
