[2024-06-28T21:28:48.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T21:28:48.618+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:28:45.008298+00:00 [queued]>
[2024-06-28T21:28:48.626+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:28:45.008298+00:00 [queued]>
[2024-06-28T21:28:48.626+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T21:28:48.639+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 21:28:45.008298+00:00
[2024-06-28T21:28:48.646+0000] {standard_task_runner.py:63} INFO - Started process 331 to run task
[2024-06-28T21:28:48.649+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T21:28:45.008298+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp52k9x09m']
[2024-06-28T21:28:48.651+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask data_delivery
[2024-06-28T21:28:48.690+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:28:45.008298+00:00 [running]> on host 79a59ce16f65
[2024-06-28T21:28:48.938+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T21:28:45.008298+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T21:28:45.008298+00:00'
[2024-06-28T21:28:48.939+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T21:28:48.952+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T21:28:48.952+0000] {Load_Data.py:20} INFO - Loading location Dimension ...
[2024-06-28T21:28:48.959+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:28:48.962+0000] {Load_Data.py:36} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T21:28:49.136+0000] {Table_creation.py:51} INFO - Loading data into table DimLocation...
[2024-06-28T21:28:49.139+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:28:49.140+0000] {Load_Data.py:89} INFO - Error loading location dimension: duplicate key value violates unique constraint "dimlocation_pkey"
DETAIL:  Key (locationid, version)=(1, 1) already exists.

[2024-06-28T21:28:49.141+0000] {Load_Data.py:94} INFO - loading DimRate Dimension ...
[2024-06-28T21:28:49.143+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T21:28:49.146+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:28:49.154+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T21:28:49.154+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:28:49.154+0000] {Load_Data.py:97} INFO - DimRate_df dimension loaded successfully
[2024-06-28T21:28:49.154+0000] {Load_Data.py:112} INFO - loading payment dimension....
[2024-06-28T21:28:49.156+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T21:28:49.159+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:28:49.164+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T21:28:49.165+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:28:49.165+0000] {Load_Data.py:115} INFO - payment_df dimension loaded successfully
[2024-06-28T21:28:49.166+0000] {Load_Data.py:11} INFO - loading Dimvendor Dimension ...
[2024-06-28T21:28:49.168+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-28T21:28:49.171+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:28:49.175+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-28T21:28:49.176+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:28:49.176+0000] {Load_Data.py:14} INFO - Dimvedor_df dimension loaded successfully
[2024-06-28T21:28:49.176+0000] {Load_Data.py:103} INFO - loading trip_type dimension....
[2024-06-28T21:28:49.178+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T21:28:49.181+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:28:49.186+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T21:28:49.186+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:28:49.186+0000] {Load_Data.py:106} INFO - trip_df dimension loaded successfully
[2024-06-28T21:28:49.187+0000] {Load_Data.py:121} INFO - loading fact table ....
[2024-06-28T21:28:52.581+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T21:28:52.584+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:31:48.432+0000] {Table_creation.py:45} INFO - Data loaded successfully into table Fact_Trip With 618792 Row
[2024-06-28T21:31:48.432+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:31:54.140+0000] {Load_Data.py:143} INFO - Fact_df  loaded successfully
[2024-06-28T21:31:54.169+0000] {NYC_Taxi_pipeline.py:61} INFO - data_delivery done
[2024-06-28T21:31:54.170+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T21:31:54.171+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T21:31:54.179+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-28T21:28:45.008298+00:00, execution_date=20240628T212845, start_date=20240628T212848, end_date=20240628T213154
[2024-06-28T21:31:54.241+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T21:31:54.255+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T21:31:54.257+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
