[2024-06-28T23:02:59.607+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T23:02:59.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T23:02:54.859104+00:00 [queued]>
[2024-06-28T23:02:59.643+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T23:02:54.859104+00:00 [queued]>
[2024-06-28T23:02:59.644+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T23:02:59.659+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 23:02:54.859104+00:00
[2024-06-28T23:02:59.667+0000] {standard_task_runner.py:63} INFO - Started process 511 to run task
[2024-06-28T23:02:59.671+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T23:02:54.859104+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpdyff46_4']
[2024-06-28T23:02:59.675+0000] {standard_task_runner.py:91} INFO - Job 179: Subtask data_delivery
[2024-06-28T23:02:59.729+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T23:02:54.859104+00:00 [running]> on host 79a59ce16f65
[2024-06-28T23:03:00.022+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T23:02:54.859104+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T23:02:54.859104+00:00'
[2024-06-28T23:03:00.023+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T23:03:00.035+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T23:03:00.036+0000] {Load_Data.py:20} INFO - Loading location Dimension ...
[2024-06-28T23:03:00.045+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T23:03:00.049+0000] {Load_Data.py:36} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T23:03:00.054+0000] {db_utils.py:37} INFO - Query executed successfully for table DimLocation
[2024-06-28T23:03:00.054+0000] {Load_Data.py:62} INFO - Updated row
[2024-06-28T23:03:00.204+0000] {db_utils.py:37} INFO - Query executed successfully for table DimLocation
[2024-06-28T23:03:00.205+0000] {Load_Data.py:62} INFO - Updated row
[2024-06-28T23:03:00.206+0000] {db_utils.py:37} INFO - Query executed successfully for table DimLocation
[2024-06-28T23:03:00.206+0000] {Load_Data.py:62} INFO - Updated row
[2024-06-28T23:03:00.209+0000] {db_utils.py:37} INFO - Query executed successfully for table DimLocation
[2024-06-28T23:03:00.209+0000] {Load_Data.py:62} INFO - Updated row
[2024-06-28T23:03:00.210+0000] {db_utils.py:37} INFO - Query executed successfully for table DimLocation
[2024-06-28T23:03:00.210+0000] {Load_Data.py:62} INFO - Updated row
[2024-06-28T23:03:00.210+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T23:03:00.211+0000] {Table_creation.py:51} INFO - Loading data into table DimLocation...
[2024-06-28T23:03:00.214+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T23:03:00.216+0000] {Load_Data.py:96} INFO - Error loading location dimension: duplicate key value violates unique constraint "dimlocation_pkey"
DETAIL:  Key (locationid, version)=(1, 2) already exists.

[2024-06-28T23:03:00.216+0000] {Load_Data.py:101} INFO - loading DimRate Dimension ...
[2024-06-28T23:03:00.219+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T23:03:00.222+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T23:03:00.228+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T23:03:00.228+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T23:03:00.228+0000] {Load_Data.py:104} INFO - DimRate_df dimension loaded successfully
[2024-06-28T23:03:00.228+0000] {Load_Data.py:119} INFO - loading payment dimension....
[2024-06-28T23:03:00.230+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T23:03:00.232+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T23:03:00.239+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T23:03:00.239+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T23:03:00.239+0000] {Load_Data.py:122} INFO - payment_df dimension loaded successfully
[2024-06-28T23:03:00.239+0000] {Load_Data.py:11} INFO - loading Dimvendor Dimension ...
[2024-06-28T23:03:00.241+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-28T23:03:00.244+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T23:03:00.249+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-28T23:03:00.249+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T23:03:00.249+0000] {Load_Data.py:14} INFO - Dimvedor_df dimension loaded successfully
[2024-06-28T23:03:00.249+0000] {Load_Data.py:110} INFO - loading trip_type dimension....
[2024-06-28T23:03:00.252+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T23:03:00.255+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T23:03:00.259+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T23:03:00.259+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T23:03:00.259+0000] {Load_Data.py:113} INFO - trip_df dimension loaded successfully
[2024-06-28T23:03:00.260+0000] {Load_Data.py:128} INFO - loading fact table ....
[2024-06-28T23:03:04.053+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T23:03:04.056+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T23:05:05.850+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T23:05:05.852+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T23:05:05.853+0000] {process_utils.py:132} INFO - Sending 15 to group 511. PIDs of all processes in the group: [511]
[2024-06-28T23:05:05.853+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 511
[2024-06-28T23:05:05.854+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T23:05:05.854+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T23:05:06.026+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=511, status='terminated', exitcode=0, started='23:02:59') (511) terminated with exit code 0
