[2024-06-28T21:32:15.737+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T21:32:15.759+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:32:12.545659+00:00 [queued]>
[2024-06-28T21:32:15.768+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:32:12.545659+00:00 [queued]>
[2024-06-28T21:32:15.768+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T21:32:15.779+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 21:32:12.545659+00:00
[2024-06-28T21:32:15.786+0000] {standard_task_runner.py:63} INFO - Started process 340 to run task
[2024-06-28T21:32:15.789+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T21:32:12.545659+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpokxuscc0']
[2024-06-28T21:32:15.791+0000] {standard_task_runner.py:91} INFO - Job 122: Subtask data_delivery
[2024-06-28T21:32:15.836+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T21:32:12.545659+00:00 [running]> on host 79a59ce16f65
[2024-06-28T21:32:16.079+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T21:32:12.545659+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T21:32:12.545659+00:00'
[2024-06-28T21:32:16.080+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T21:32:16.092+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T21:32:16.092+0000] {Load_Data.py:21} INFO - Loading location Dimension ...
[2024-06-28T21:32:16.099+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:32:16.104+0000] {Load_Data.py:36} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T21:32:16.277+0000] {Table_creation.py:51} INFO - Loading data into table DimLocation...
[2024-06-28T21:32:16.280+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:32:16.282+0000] {Load_Data.py:90} INFO - Error loading location dimension: duplicate key value violates unique constraint "dimlocation_pkey"
DETAIL:  Key (locationid, version)=(1, 1) already exists.

[2024-06-28T21:32:16.283+0000] {Load_Data.py:95} INFO - loading DimRate Dimension ...
[2024-06-28T21:32:16.286+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T21:32:16.288+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:32:16.325+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T21:32:16.325+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:32:16.326+0000] {Load_Data.py:98} INFO - DimRate_df dimension loaded successfully
[2024-06-28T21:32:16.326+0000] {Load_Data.py:113} INFO - loading payment dimension....
[2024-06-28T21:32:16.327+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T21:32:16.330+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:32:16.348+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T21:32:16.349+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:32:16.349+0000] {Load_Data.py:116} INFO - payment_df dimension loaded successfully
[2024-06-28T21:32:16.349+0000] {Load_Data.py:11} INFO - loading Dimvendor Dimension ...
[2024-06-28T21:32:16.351+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-28T21:32:16.354+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:32:16.359+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-28T21:32:16.359+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:32:16.359+0000] {Load_Data.py:14} INFO - Dimvedor_df dimension loaded successfully
[2024-06-28T21:32:16.359+0000] {Load_Data.py:104} INFO - loading trip_type dimension....
[2024-06-28T21:32:16.362+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T21:32:16.366+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:32:16.371+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T21:32:16.371+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:32:16.371+0000] {Load_Data.py:107} INFO - trip_df dimension loaded successfully
[2024-06-28T21:32:16.371+0000] {Load_Data.py:122} INFO - loading fact table ....
[2024-06-28T21:32:19.879+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T21:32:19.883+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T21:35:22.232+0000] {Table_creation.py:45} INFO - Data loaded successfully into table Fact_Trip With 618792 Row
[2024-06-28T21:35:22.233+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T21:35:28.123+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T21:35:28.125+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T21:35:28.127+0000] {process_utils.py:132} INFO - Sending 15 to group 340. PIDs of all processes in the group: [340]
[2024-06-28T21:35:28.127+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 340
[2024-06-28T21:35:28.128+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T21:35:28.187+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T21:35:28.300+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=340, status='terminated', exitcode=0, started='21:32:15') (340) terminated with exit code 0
